# Generated by Django 4.0.5 on 2022-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_command_user_alter_user_card_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user',
        ),
        migrations.AddField(
            model_name='command',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
