# Generated by Django 4.0.5 on 2022-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_trip_date_time_alter_trip_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price_promotion',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
