# Generated by Django 4.0.5 on 2022-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_article_price_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
